### PR TITLE
fix version number in getting-started/installation

### PR DESCRIPTION
**Pull request by Ryoga-exe**
Resolve: #271

Fix the page for installing Zig 0.13.0. (https://zig.guide/getting-started/installation)

I have replaced all instances of 0.12.0 with 0.13.0.

### CODE REVIEW

**Review by sonicfromnewyoke — CHANGES_REQUESTED** [review]
agree with the changes for `0.13` version of docs, but I believe `0.14` version of the guide should use `0.14.0` [version of zig](https://ziglang.org/download/)

**Comment by Ryoga-exe** [comment]
> agree with the changes for `0.13` version of docs, but I believe `0.14` version of the guide should use `0.14.0` [version of zig](https://ziglang.org/download/)

I fixed it.

**Review by sonicfromnewyoke — CHANGES_REQUESTED** [review]
`0.14` version is a current `master`, so you can't replace a number in  so a straightforward way.
for windows it should be `zig-windows-x86_64-0.14.0-dev.1954+2d888a8e6`

**Comment by Ryoga-exe** [comment]
> `0.14` version is a current `master`, so you can't replace a number in so a straightforward way. for windows it should be `zig-windows-x86_64-0.14.0-dev.1954+2d888a8e6`

I fixed it.

Since it's not available through the package manager, I commented out that section. I also added a section on installing the master dev build on Windows using Scoop.

**Review by sonicfromnewyoke — APPROVED** [review]
LGTM

**Comment by Sobeston** [comment]
Sorry for the delay, closed in favour of a385cc7b5d7062afc143c44181d57c65de3b67e5 and 78ed7af72fa9e20555c125e1c9e4c6cf8947c44a. Was unsure about the changes to the windows install instructions for 0.14.

**Pull request closed without merging**
